language: node_js
node_js:
  - '8'
  - '10'
  - '12'
  - 'lts/*'
  - 'node'

matrix:
  include:
    - node_js: '8'
      env: NO_LINT=true

script:
  - if [[ -z "$NO_LINT" ]]; then npm run lint; fi
  - npm test
